### ISSUE TITLE
А это зачем?

### ISSUE THREAD

**Issue by PetrovIliya** [eCREATORx/practice2021#10]
https://github.com/eCREATORx/practice2021/blob/5bfdb43bb3e146c397161d9e86f6e140f246a504/public/App/Component/ManagerSignatureForm/ManagerSignatureForm.js#L29

**Comment by eCREATORx** [comment]
В React не рекомендуется использовать вложенные объекты в state компонента, так что сделать данную переменную частью state не представляется возможным
